# env:
#   global:
#     - "FTP_USER=adkave_travis"
#     - "FTP_PASSWORD=m3m3dotcom"
branches:
  only: master

language: node_js
node_js: 
  - "stable"

before_install:
  - 'npm install -g grunt-cli bower'
  - 'gem install jekyll'
  - 'gem install compass'

install: 
  - 'bower install'
  - 'npm install'

script:
  - 'grunt build'

after_success:
#  - 'cd _site && find . -type f -exec curl -u $FTP_USER:$FTP_PASSWORD --ftp-create-dirs -T {} ftp://nogorweb.com/{} \;'
  - 'echo Done :D'