# Site settings
title: Galaxy IT
url: "http://glaxyit.adkave.com/"

logo: 'img/adkave.png'

client_slug: 'galaxyit' # slug for the sql table name

second-logo:
  img: 'img/logo.png'
  title: 'Galaxy IT'
  text: >
    <i class="fa fa-globe"></i> IT solutions from a different Galaxy

slides:
  - caption: 'Slide 1'
    thumb: ''
    img: 'img/responsive.jpeg'

desc:
  type: para
  heading: Best IT solutions in the galaxy
  text: >
    <p>Galaxy IT provides the best IT solutions</p>
# type: table
# title: Awesome Item
# price: '1,000,000'
# warn: a very nice warning to spammers
# items:
#   - icon: car
#     text: Dodge Charger

adsense: #ad codes goes here, adsense or otherwise

analytics: UA-61372863-1

footer:
  credits: 'Adkave'
  links:
    - link: '//adkave.com'
      text: 'Adkave'
    - link: '//'

###############################################################################
# Build settings
markdown: kramdown

permalink: ''
defaults:
  -
    scope:
      path: ''
    values:
      layout: default

exclude:
  - 'node_modules'
  - 'components'
  - 'src'
  - 'config.rb'
  - 'Gruntfile.js'
  - 'package.js'
  - 'bower.json'
  - 'README.md'
